### ISSUE TITLE
VOD solution

### ISSUE THREAD

**Issue by emilorol** [arut/nginx-ts-module#12]
Hi,

I am trying to build a VOD solution using nginx and one of your modules. RTMP module seems to be stuck with Flash as HTML 5 will not support it. HLS seems to be the way to go specially with mobile devices.

Case scenario:

I have a lot of videos ( MP4 ) and I want them to be accesible thru the web either thru a computer and mobile device ( HTML5 ). Which of your module I can use to accomplish this?

Note: I was able to make it work with your RTMP module, but unless you can recommend me a better RTMP HTML 5 player, JW Player worked on my desktop, but got stuck on my mobile.

**Comment by arut** [comment]
- If you have mp4 files you don't need any modules to play those files. All browsers support playing mp4 and use HTTP Range requests to be efficient.
- HLS/DASH is more efficient for mobile playback since media is delivered in small pieces.
- None of my __public__ modules support VOD HLS. You can buy nginx-plus from Nginx Inc with a VOD HLS module which turns mp4 to HLS on the fly.
